FROM debian:stable-slim


ARG DB_SERVER_NAME
ARG DB_DATABASE_NAME
ARG DB_DATABASE_TYPE
ARG DB_DATABASE_USERNAME
ARG DB_DATABASE_PASSWORD
ARG DB_DATABASE_SECRET_KEY
ARG AWS_REGION




ENV DB_DATABASE_TYPE=$DB_DATABASE_TYPE
ENV DB_DATABASE_SECRET_KEY=$DB_DATABASE_SECRET_KEY
ENV AWS_REGION=$AWS_REGION
ENV DB_SERVER_NAME=$DB_SERVER_NAME
ENV DB_DATABASE_USERNAME=$DB_DATABASE_USERNAME
ENV DB_DATABASE_PASSWORD=$DB_DATABASE_PASSWORD
ENV DB_DATABASE_SECRET_KEY=$DB_DATABASE_SECRET_KEY
ENV DB_DATABASE_NAME=$DB_DATABASE_NAME



COPY server .
ENTRYPOINT ["./server"]

