# Create NameSpace

apiVersion: v1
kind: Namespace
metadata:
  name: intuit-interview-development
  labels:
    name: intuit-interview-development
---

# Service
apiVersion: v1
kind: Service
metadata:
  namespace: "intuit-interview-development"
  name: intuit-interview-development-service
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: intuit-interview
    release: intuit-interview


---
# External Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "intuit-interview-development"
  name: intuit-interview-development-ingress
  labels:
    app: intuit-interview
    release: intuit-interview
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: intuit-demo.prophesionalizm.net
      http:
        paths:
          - path: /api
            backend:
              serviceName: intuit-interview-development-service
              servicePort: 8088
